### PR TITLE
Added options panel for the extension

### LINKED ISSUE #44: Add extension settings page
It would be nice to have a settings page for the extension that allows the user to choose which parts of Seneca Blackboard they want to toggle.

### PR DESCRIPTION
**Pull request by Casva**
Fixes #44 

Took some time and a lot of reading but the options panel is now functioning for the extension!

I had to rearrange some of the code in order for it to work.

- ```Background,js``` was added to run as the default script 
- Each feature was moved into its own file and put under a features folder for better organization
- I have it programmed for now that the user has to refresh the page in order for the changes to be seen
- **There seems to be an issue where the options panel twitches for a bit sometimes when you open it (cannot seem to find the problem, was hoping someone else would have an idea)

Let me know if any changes need to be made!

### CODE REVIEW

**Comment by yevseytsev** [comment]
@Casva please fix conflicts

**Comment by Casva** [comment]
@yevseytsev sure, it does require some time to rebase though since a bunch of new code has been added in since the initial request.

**Comment by Casva** [comment]
@yevseytsev merge conflicts have been fixed!

**Comment by yevseytsev** [comment]
@Casva thank you!

**Pull request merged**
