### PR TITLE
Fixed buttons not working error

### PR DESCRIPTION
**Pull request by YuechengWu**
The functions were deleted for some reason. I added them and got it to work on my local machine. Let me know if it still has errors.

### CODE REVIEW

**Comment by yevseytsev** [comment]
@YuechengWu please fix a conflict

**Comment by yevseytsev** [comment]
@YuechengWu thank you!

**Comment by YuechengWu** [comment]
@yevseytsev Those buttons are not showing up after the merge conflict fixed, I will look into it later.

**Comment by yevseytsev** [comment]
@YuechengWu okay, create a new issue for it please

**Pull request merged**
